"""removed the role column

Revision ID: 4a8a1f3a7af5
Revises: 
Create Date: 2024-08-24 12:47:03.976202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a8a1f3a7af5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=200), nullable=False))

    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=200), nullable=False))

    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
