"""added frequency

Revision ID: 58117e69b69b
Revises: f66822c41842
Create Date: 2024-08-22 18:11:00.080214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58117e69b69b'
down_revision = 'f66822c41842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
