"""added admin flag nullable false

Revision ID: 5a18923964c8
Revises: b89496c58852
Create Date: 2024-08-24 10:02:47.396133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a18923964c8'
down_revision = 'b89496c58852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
