"""updated models

Revision ID: 76f5ead29784
Revises: 58117e69b69b
Create Date: 2024-08-24 09:38:12.302498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76f5ead29784'
down_revision = '58117e69b69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.drop_column('companyname')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('companyname', mysql.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
