"""updated models again

Revision ID: b89496c58852
Revises: 76f5ead29784
Create Date: 2024-08-24 09:40:06.501027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89496c58852'
down_revision = '76f5ead29784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_company_id', 'adminuser', ['company_id'], ['admin_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectoruser', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
