"""resolve unique features

Revision ID: f66822c41842
Revises: 65d1ec900a69
Create Date: 2024-08-20 13:13:50.954534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66822c41842'
down_revision = '65d1ec900a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.drop_index('firstname')
        batch_op.drop_index('secondname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseuser', schema=None) as batch_op:
        batch_op.create_index('secondname', ['secondname'], unique=True)
        batch_op.create_index('firstname', ['firstname'], unique=True)

    # ### end Alembic commands ###
