"""added route id

Revision ID: fecbc544a68c
Revises: ac9d872f3af9
Create Date: 2024-09-01 15:15:54.160139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecbc544a68c'
down_revision = 'ac9d872f3af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseclient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_route_id_client', 'routes', ['route_id'], ['route_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houseclient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_id_client', type_='foreignkey')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
